echo Exporting data_sim data to .csv files...

echo exporting usage data...
psql -f export_usage.sql xray

echo exporting alert data...
psql -f export_alert.sql xray

echo export attribute sp data...
psql -f export_attribute_sp.sql xray

echo export attribute connection history data...
psql -f export_attribute_connection_hist.sql xray

echo export attribute meter history data...
psql -f export_attribute_meter_hist.sql xray

echo done.
