INSERT INTO grid.calc_method 
VALUES 
('SP_ELEC_INT_MAIN','SERVICE_PT_ELEC','INTERVAL',1,'USAGE_SINGULAR','GRID.USAGE','GRID.CALC'),
('SP_GAS_INT_MAIN','SERVICE_PT_GAS','INTERVAL',1,'USAGE_SINGULAR','GRID.USAGE','GRID.CALC'),
('SP_ELEC_AR_MAIN','SERVICE_PT_ELEC','DAILY_SCALAR',2,'USAGE_SINGULAR','GRID.USAGE','GRID.CALC'),
('SP_GAS_AR_MAIN','SERVICE_PT_GAS','DAILY_SCALAR',3,'USAGE_SINGULAR','GRID.USAGE','GRID.CALC'),
('SP_ELEC_MR_MAIN','SERVICE_PT_ELEC','MONTHLY_SCALAR',4,'USAGE_SINGULAR','GRID.USAGE','GRID.CALC'),
('SP_GAS_MR_MAIN','SERVICE_PT_GAS','MONTHLY_SCALAR',5,'USAGE_SINGULAR','GRID.USAGE','GRID.CALC')
;