INSERT INTO grid.condition_code 
VALUES 
('UPSIDE_DOWN_METER','REVERSE_USAGE',30,'Upside Down Meter'), 
('REVERSE_ROTATION','REVERSE_USAGE',30,'Reverse Rotation'), 
('REVERSE_USAGE','REVERSE_USAGE',30,'Reverse Usage'), 
('CRITICAL_TAMPER','TAMPER_SEVERE',30,'Critical Tamper'), 
('MAGNETIC_TAMPER','TAMPER_SEVERE',30,'Magnetic Tamper'), 
('METER_REMOVAL_UNEXPECTED','TAMPER_SEVERE',30,' Meter Removal - Unexpected'), 
('LOAD_SIDE_VOLTAGE_ON_DISCONNECT','LOAD_SIDE_VOLTAGE_ON_DISCONNECT',14,' Load Side Voltage Detected on Disconnected Meter'), 
('LOAD_SIDE_VOLTAGE_ON_DISCONNECT_BEFORE_REMOVAL','LOAD_SIDE_VOLTAGE_ON_DISCONNECT',14,'Load Side Voltage Detected Before Meter was Removed'), 
('USAGE_ON_DISCONNECT','USAGE_ON_DISCONNECT',45,'Usage on Disconnected Service'), 
('USAGE_ON_DISCONNECT_BEFORE_REMOVAL','USAGE_ON_DISCONNECT',45,'Usage on Disconnected Service Before Meter Was Removed'), 
('USAGE_DEVIATION_VERY_HIGH','ABNORMAL_USAGE',7,'Usage Deviation - Very High'), 
('USAGE_DEVIATION_HIGH','ABNORMAL_USAGE',7,'Usage Deviation - High'), 
('USAGE_DEVIATION_LOW','ABNORMAL_USAGE',7,'Usage Deviation - Low'), 
('USAGE_DEVIATION_VERY_LOW','ABNORMAL_USAGE',7,'Usage Deviation - Very Low'), 
('USAGE_DEVIATION_AFTER_METER_CHANGE','ABNORMAL_USAGE',7,'Usage Deviation - After Meter Change'), 
('USAGE_HIGHEST_RECORDED','ABNORMAL_USAGE',7,'Highest Recorded Usage for Meter'), 
('USAGE_LOWEST_RECORDED','ABNORMAL_USAGE',7,'Lowest Recorded Usage for Meter'), 
('NEGATIVE_USAGE_EXTREME','ABNORMAL_USAGE',7,'Negative Usage - Extreme'), 
('WEATHER_DEVIATION_HIGH','WEATHER_DEVIATION',7,'Usage Deviation from Weather - High'), 
('WEATHER_DEVIATION_LOW','WEATHER_DEVIATION',7,'Usage Deviation from Weather - Low'), 
('ZERO_USAGE_AFTER_METER_CHANGE','ZERO_USAGE',14,'Zero Usage - After Meter Change'), 
('ZERO_USAGE_WITH_HIGH_HISTORY','ZERO_USAGE',7,'Zero Usage - with High Historical Usage'), 
('ZERO_USAGE_NORMAL','ZERO_USAGE',7,'Zero Usage - Normal'), 
('AMI_COMM_LOSS_AFTER_REMOTE_DISCONNECT','MISSING_USAGE',14,'AMI Communication Loss - after Remote Disconnect'), 
('AMI_COMM_LOSS_AFTER_FIELD_DISCONNECT','MISSING_USAGE',14,'AMI Communication Loss - after Field Disconnect'), 
('MISSING_USAGE_EXTENDED','MISSING_USAGE',14,'Missing Usage - Extended Period'), 
('OUTAGE_SUSTAINED_EVENT','OUTAGE_SUSTAINED',7,'Outage Sustained - Detected from Event'), 
('OUTAGE_SUSTAINED_INTERVAL','OUTAGE_SUSTAINED',7,'Outage Sustained - Detected from Intervals'), 
('OUTAGE_SUSTAINED_OMS','OUTAGE_SUSTAINED',7,'Outage Sustained - Detected from OMS'), 
('OUTAGE_MOMENTARY','OUTAGE_POTENTIAL',7,'Outage Potential'), 
('LOW_VOLTAGE_REPETITIVE','POWER_QUALITY',7,'Low Voltage - Repetitive'), 
('LOW_VOLTAGE_POTENTIAL','POWER_QUALITY',7,'Low Voltage - Potential'), 
('LOW_VOLTAGE_NEVER_CLOSED_3PHASE','POWER_QUALITY',7,'Low Voltage - Never Closed on 3 Phase Service'), 
('LOW_VOLTAGE_HIGH_FLUCTUATION','POWER_QUALITY',7,'Low Voltage - High Fluctuation'), 
('ZERO_REACTIVE_USAGE','POWER_QUALITY',7,'Zero Reactive Usage'), 
('POWER_FACTOR_POOR','POWER_FACTOR',7,'Power Factor Poor'), 
('MEMORY_FAILURE_CRITICAL','METER_MEMORY_FAILURE',7,'Meter Memory Failure - Critical'), 
('MEMORY_FAILURE_POTENTIAL','METER_MEMORY_FAILURE',7,'Meter Memory Failure - Potential'), 
('OVERLOADED_CRITICAL','OVERLOADED_SERVICE',14,'Overloaded Service - Critical'), 
('OVERLOADED_POTENTIAL','OVERLOADED_SERVICE',14,'Overloaded Service - Potential'), 
('DISTRBUTION_LOSS_CRITICAL','DISTRIBUTION_LOSS',14,'Distribution Loss - Critical') 
;